### ISSUE TITLE
Readme Commands Don't Work w/ Ubunutu Server 14.04.2 Server 64bit

### ISSUE THREAD

**Issue by kevroy314** [mit-probabilistic-computing-project/crosscat#31]
Running the commands (plus sudo apt-get install git to get git) listed in the readme result in errors in a fresh virtual machine running in Hyper-V on Windows 8.1 64bit.

When attempting a build of setup.py, "error:command 'x86_64-linux-gnu-gcc' failed with exit status 1\r\nerror typing to exec 'cc1plus': execvp: No such file or directory" error occurs, ending the build.

When attempting to install after that, the same error occurs.

When attempting to run the example code, "ImportError: No module named crosscat.settings" occurs.

When attempting the pip install variation (obviously now running sudo apt-get install python-pip before attempting), the install loops through the same warning for many many modules "cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for c++ [enabled by default]".

Seems like it shouldn't be this hard to get this thing to run.

**Comment by BaxterEaves** [comment]
I'm sorry things aren't working. Without seeing the full trace, `ImportError` leads me to believe that crosscat is not compiling though I can't be sure.  `-Wstrict-prototypes' is valid for C/ObjC but not for c++` is a harmless (albeit annoying) warning, so that's not the problem. Could you paste in the full trace from the install and also the commands that produce that error?

**Comment by riastradh-probcomp** [comment]
Date: Wed, 13 May 2015 05:30:01 -0700
   From: Baxter Eaves <notifications@github.com>

   I'm sorry things aren't working. Without seeing the full trace,
   `ImportError` leads me to believe that crosscat is not compiling
   though I can't be sure.  `-Wstrict-prototypes' is valid for C/ObjC
   but not for c++` is a harmless (albeit annoying) warning, so that's
   not the problem. Could you paste in the full trace from the install
   and also the commands that produce that error?

It sounds like the C++ compiler is missing.  `apt-get install
build-essential' should help.

**Comment by gregory-marton** [comment]
Closing because this seems stale.

**Comment by riastradh-probcomp** [comment]
Addressed in 97a9072a5ace0bfc9ed0c043e0cda19270cd2295.
