### ISSUE TITLE
Build success with Mac OS X

### ISSUE THREAD

**Issue by prb** [mit-probabilistic-computing-project/crosscat#32]
Just wanted to share a build success with other Mac OS users:

- Install Boost via MacPorts.
- Set up Python virtualenv.
- Edit `setup.py`, replacing `boost_random` with `boost_random-mt` throughout.
- Build with:

```
BOOST_ROOT=/opt/local CPLUS_INCLUDE_PATH=/opt/local/include python setup.py build
BOOST_ROOT=/opt/local CPLUS_INCLUDE_PATH=/opt/local/include python setup.py install
```

**Comment by gregory-marton** [comment]
Is there a bug or feature request here?

**Comment by prb** [comment]
There are several, I think, but all focused on documentation.  You could regard the above success story as a proposed patch for documentation.  It is also the case that I only went that route because none of the examples work with the docker image.

**Comment by riastradh-probcomp** [comment]
The boost_random issue is basically a bug in MacPorts, that it does not install the non-mt versions of the boost libraries, not even in the form of symlinks to the -mt versions.

Everywhere else, the library is in fact boost_random, and since (a) Crosscat is not multithreaded, and (b) the -mt versions of libraries are optional things to build in boost, using boost_random instead of boost_random-mt is correct.

We could just use the -mt variant on OS X, under the assumption that probably most boost builds for OS X include multithreading support, although that would be overkill for, e.g., Homebrew-installed boost, which if I recall correctly builds both variants.

**Comment by riastradh-probcomp** [comment]
No longer relevant because we need no longer link against boost (although we still use boost header files), as of ad8adbb70742ff0fcd109e494aa84537fdbb6f87.
