### ISSUE TITLE
allow columns to be forced dependent/independent

### ISSUE THREAD

**Issue by riastradh-probcomp** [mit-probabilistic-computing-project/crosscat#33]

**Comment by gregory-marton** [comment]
Can you say more? Who wants these, and for what? What's their desired behavior? Where in the code might one implement them? Are there similar features that one might start with in doing so?

**Comment by riastradh-probcomp** [comment]
The intent is that you should be able to write:

    CREATE GENERATOR foo_cc FOR foo USING crosscat (
        GUESS(*),
        INDEPENDENT(x, y),
        INDEPENDENT(x, z),
        DEPENDENT(x, w)
    )

and have, for every Crosscat state, that x and w share a view, but x and y are in different views and x and z are in different views.

Baxter partially implemented this in Crosscat on a branch, bax-ensure-and-assert, but as I recall the strategy was sleazy and the implementation probably needed more work, so it was not merged.

**Comment by fsaad** [comment]
"The strategy was sleazy and the implementation probably needed more work", can you please elaborate on this statement? What is sleazy, and which parts need more work?

The only part that is a heuristic is sampling 100 states during initialization to determine if cc can be initialized with the constraints (rather than brute forcing all partitions / or something smarter like connected components etc)

**Comment by riastradh-probcomp** [comment]
No, I can't elaborate on it -- I just remember that @BaxterEaves's feeling about it was that it was sleazy and slow.

**Comment by riastradh-probcomp** [comment]
Fixed in 0.1.21 (commit db69c5916de2420772ceafbdf5713d2662d45611).
